### ISSUE TITLE
run grunt,threw an error 

### ISSUE THREAD

**Issue by cqqxyt** [freegroup/draw2d_js.app.brainbox#2]
Running "run:gitbook" (run) task
>> Error: spawn gitbook ENOENT
Warning: non-zero exit code -4058 Use --force to continue.

Aborted due to warnings.

**Comment by freegroup** [comment]
run 

```
npm install 
```

to install all node dependencies before your start the grunt build.

**Comment by cqqxyt** [comment]
I already do this 
`npm install`
then `bower install`
last `grunt`

**Comment by freegroup** [comment]
may this helps 

```
npm install -g gitbook-cli
```
