### ISSUE TITLE
Q: Is connection code in this package?

### ISSUE THREAD

**Issue by KingKnecht** [freegroup/draw2d_js.app.brainbox#4]
Hi,
is the code for drawing and dragging the connections included  in this package or is it 3rd party?
A hint where the mouse move stuff is handled when clicked to a point or line-segment of a connection would be very nice.
Thx.

**Comment by freegroup** [comment]
check my web site for this http://www.draw2d.org or you can install the draw2d via

```
   bower install draw2d --save
```
